language: cpp
dist: xenial
env:
  global:
  - HUNTER_ROOT="${TRAVIS_BUILD_DIR}/hunter"
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
cache:
  directories:
  - "$TRAVIS_BUILD_DIR/deps"
  - "$TRAVIS_BUILD_DIR/hunter"
branches:
stages:
# - clang-format
- compile_test
jobs:
  include:
  # - stage: clang-format
    # os: linux
    # addons:
      # apt:
        # update: true
        # sources:
        # - llvm-toolchain-xenial-8
        # - ubuntu-toolchain-r-test
        # packages:
        # - clang-format-8
    # script: "./ci/run-clang-format.py -r --clang-format-executable clang-format-8
      # --color always ./developers/"
  # - stage: compile_test
    # os: linux
    # compiler: clang
    # env:
    # - COMPILER='clang++-8'
    # - BUILD_TYPE='Release'
    # addons:
      # apt:
        # sources:
        # - llvm-toolchain-xenial-8
        # - ubuntu-toolchain-r-test
        # packages:
        # - clang-8
        # - g++-7
    # script: "./ci/compile.sh"
    - stage: compile_test
      os: osx
      osx_image: xcode10.1
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Debug'
      script: "./ci/compile.sh"
  
